{
	"version": 1737699316,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bg1-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/particles.png",
		"images/particles2.png",
		"images/particles3.png",
		"images/sprite7-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/particles4.png",
		"media/collect-points-190037.m4a",
		"media/collect-points-190037.ogg",
		"media/crash.m4a",
		"media/crash.ogg",
		"media/puppy.m4a",
		"media/puppy.ogg",
		"media/game over.m4a",
		"media/game over.ogg",
		"media/elon rocket game music.m4a",
		"media/elon rocket game music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}